server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    #  instanc中的配置是让该服务使用IP注册到注册中心，而不是hostname
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则），默认30
    lease-renewal-interval-in-seconds: 10
    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己），默认90
    lease-expiration-duration-in-seconds: 15


#客户端默认是30s发送一次心跳，90s服务端没有收到心跳就把服务剔除


spring:
  application:
    name: service-config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sewer?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chunchengmeigui/config-center.git
          skipSslValidation: true #跳过校验
          basedir: D:\IDEA_DEMO\on #从git仓库拉取到的文件在本地存储的位置，可自行修改或删掉，默认存储在C盘
          username: 903321643@qq.com
          password: d903321643
          # 这里可以写死，也可以写成{profile}来动态化
          search-paths: config-client
      label: master



